export const initialConfig = {
  title: 'Venta Garage',
  subtitle: 'Nos mudamos. Todo tiene que volar.',
  sellerName: 'Ian',
  whatsapp: '+34600000000',
  bizum: '+34600000000',
  adminPassword: 'garage2026',
  currency: '€',
  categories: ['Muebles', 'Electrónica', 'Decoración', 'Deporte', 'Otros'],
};

export const initialItems = [
  {
    id: 'xiaomi-s12',
    name: 'Robot aspiradora Xiaomi S12',
    description: 'Xiaomi Robot Vacuum S12 en perfectas condiciones. Aspira y friega. Incluye estación de carga, mopa, cepillos de repuesto y todos los accesorios originales.',
    price: 0,
    category: 'Electrónica',
    sold: false,
    createdAt: 1748304000000,
    photos: [
      '/images/xiaomi-01.jpeg',
      '/images/xiaomi-02.jpeg',
      '/images/xiaomi-03.jpeg',
      '/images/xiaomi-04.jpeg',
      '/images/xiaomi-05.jpeg',
      '/images/xiaomi-06.jpeg',
      '/images/xiaomi-07.jpeg',
    ],
  },
  {
    id: 'weber-grill',
    name: 'Parrilla Weber',
    description: 'Barbacoa Weber en buen estado. Incluye parrilla y tapa. Ideal para exteriores o terraza.',
    price: 0,
    category: 'Deporte',
    sold: false,
    createdAt: 1748304001000,
    photos: [
      '/images/weber-01.jpeg',
      '/images/weber-02.jpeg',
      '/images/weber-03.jpeg',
    ],
  },
  {
    id: 'escritorio',
    name: 'Set escritorio completo + silla',
    description: 'Escritorio con base y pantalla incluida más silla de escritorio. Conjunto completo para home office.',
    price: 0,
    category: 'Muebles',
    sold: false,
    createdAt: 1748304002000,
    photos: [
      '/images/escritorio-01.jpeg',
      '/images/escritorio-02.jpeg',
      '/images/escritorio-03.jpeg',
    ],
  },
  {
    id: 'lamparas',
    name: 'Set lámparas de pie',
    description: 'Set de lámparas de pie con pantalla de tela plisada y patas de metal. Diseño nórdico. Buen estado.',
    price: 0,
    category: 'Decoración',
    sold: false,
    createdAt: 1748304003000,
    photos: [
      '/images/lamparas-01.jpeg',
      '/images/lamparas-02.jpeg',
      '/images/lamparas-03.jpeg',
      '/images/lamparas-04.jpeg',
      '/images/lamparas-05.jpeg',
    ],
  },
  {
    id: 'cuadros',
    name: 'Pack cuadros decoración',
    description: 'Pack de cuadros decorativos incluyendo panel de pared grande con diseño geométrico. Perfecto para salón o pasillo.',
    price: 0,
    category: 'Decoración',
    sold: false,
    createdAt: 1748304004000,
    photos: [
      '/images/cuadros-01.jpeg',
      '/images/cuadros-02.jpeg',
      '/images/cuadros-03.jpeg',
      '/images/cuadros-04.jpeg',
      '/images/cuadros-05.jpeg',
    ],
  },
  {
    id: 'espejo',
    name: 'Espejo decorativo',
    description: 'Espejo con marco de madera. Diseño elegante. Buen estado.',
    price: 0,
    category: 'Decoración',
    sold: false,
    createdAt: 1748304005000,
    photos: [
      '/images/espejo-01.jpeg',
      '/images/espejo-02.png',
    ],
  },
  {
    id: 'mesa-recibidor',
    name: 'Mesa de recibidor',
    description: 'Mesa consola para recibidor. Buen estado.',
    price: 0,
    category: 'Muebles',
    sold: false,
    createdAt: 1748304006000,
    photos: [
      '/images/recibidor-01.jpeg',
      '/images/recibidor-02.jpeg',
    ],
  },
  {
    id: 'ventilador-ikohs',
    name: 'Ventilador IKOHS',
    description: 'Ventilador de torre IKOHS con mando a distancia. Silencioso. Incluye control remoto.',
    price: 0,
    category: 'Electrónica',
    sold: false,
    createdAt: 1748304007000,
    photos: [
      '/images/ventilador-01.jpeg',
      '/images/ventilador-02.jpeg',
      '/images/ventilador-03.jpeg',
    ],
  },
  {
    id: 'cargador',
    name: 'Base cargador inalámbrico',
    description: 'Base de carga inalámbrica. Compatible con dispositivos Qi.',
    price: 0,
    category: 'Electrónica',
    sold: false,
    createdAt: 1748304008000,
    photos: [
      '/images/cargador-01.jpeg',
    ],
  },
  {
    id: 'cajonera',
    name: 'Cajonera',
    description: 'Cajonera con varios cajones. Buen estado.',
    price: 0,
    category: 'Muebles',
    sold: false,
    createdAt: 1748304009000,
    photos: [
      '/images/cajonera-01.jpeg',
    ],
  },
  {
    id: 'comoda',
    name: 'Cómoda',
    description: 'Cómoda blanca/beige. Buen estado. Con cajones.',
    price: 0,
    category: 'Muebles',
    sold: false,
    createdAt: 1748304010000,
    photos: [
      '/images/comoda-01.jpeg',
      '/images/comoda-02.jpeg',
      '/images/comoda-03.jpeg',
    ],
  },
  {
    id: 'mesa-noche',
    name: 'Mesa de noche',
    description: 'Mesita de noche. Buen estado.',
    price: 0,
    category: 'Muebles',
    sold: false,
    createdAt: 1748304011000,
    photos: [
      '/images/mesa-noche-01.jpeg',
      '/images/mesa-noche-02.jpeg',
    ],
  },
  {
    id: 'mesa-centro',
    name: 'Mesa de centro',
    description: 'Mesa de centro de madera. Sobre de madera natural. Buen estado.',
    price: 0,
    category: 'Muebles',
    sold: false,
    createdAt: 1748304012000,
    photos: [
      '/images/mesa-centro-01.jpeg',
      '/images/mesa-centro-02.jpeg',
      '/images/mesa-centro-03.jpeg',
    ],
  },
  {
    id: 'mesa-regalo',
    name: 'Mesita lateral',
    description: 'Mesita lateral / mesa de regalo. Buen estado.',
    price: 0,
    category: 'Muebles',
    sold: false,
    createdAt: 1748304013000,
    photos: [
      '/images/mesa-regalo-01.jpeg',
      '/images/mesa-regalo-02.jpeg',
    ],
  },
];
